version: '3.8'

networks:
  # Specify the network for bridging
  app-network:
    driver: bridge

services:
  frontend:
    build: .
    # command: yarn run dev
    environment:
      VUE_APP_ENV: 'development' # development production
    # volumes:
    #   - './frontend/docker.nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '80:80'
    restart: always
    networks:
      - app-network
  db:
    image: mysql:5.7.16
    # image: ibex/debian-mysql-server-5.7
    # Set mysqld charset
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASS}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_DATABASE: '${DB_NAME}'
    volumes:
      - './mysql/data:/var/lib/mysql'
      - './mysql/conf.d:/etc/mysql/conf.d'
    ports:
      - '3306:3306'
    restart: always
    networks:
      - app-network