version: '3.8'

networks:
  # Specify the network for bridging
  app-network:
    driver: bridge

services:
  dashobard:
    build: .
    # command: yarn run dev
    environment:
      VUE_APP_ENV: 'development' # development production
    # volumes:
    #   - './frontend/docker.nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '80:80'
    restart: always
    networks:
      - app-network