version: '3.8'

services:
  api-history:
    build: ./history
    command: yarn run start:prod
    environment:
      NODE_ENV: 'production' # production development
      DB_HOST2: '${DB_HOST2}'
      DB_PORT2: '${DB_PORT2}'
      DB_USER2: '${DB_USER2}'
      DB_PASS2: '${DB_PASS2}'
      DB_NAME2: '${DB_NAME2}'
    # volumes:
    #   - './history/logs:/app/logs'
    ports:
      - '3005:3000'
    restart: always
  db:
    image: mysql:5.7.16
    # image: ibex/debian-mysql-server-5.7
    # Set mysqld charset
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASS}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_DATABASE: '${DB_NAME}'
    volumes:
      - './mysql/data:/var/lib/mysql'
      - './mysql/conf.d:/etc/mysql/conf.d'
    ports:
      - '3307:3306'
    restart: always
    networks:
      - app-network